version: '3.3'
services:
  spring_mysql:
    image: mysql:latest
    container_name: spring_batch
    networks:
      example_local_network:
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: 'abc123'
      MYSQL_DATABASE: 'spring-example'
      MYSQL_USER: 'test_user'
      MYSQL_PASSWORD: 'abc'
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "./data:/data"
    command: redis-server --appendonly yes

networks:
  example_local_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.7.0.0/16